"""Leads QualiFlow - Lead Storage & Client Management
Simple JSON-based storage for leads and client records.
In production, replace with PostgreSQL or similar."""

import json
import os
import uuid
from datetime import datetime

DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')
LEADS_FILE = os.path.join(DATA_DIR, 'leads.json')
CLIENTS_FILE = os.path.join(DATA_DIR, 'clients.json')
SUBMISSIONS_FILE = os.path.join(DATA_DIR, 'submissions.json')

def ensure_dirs():
    os.makedirs(DATA_DIR, exist_ok=True)
    for f in [LEADS_FILE, CLIENTS_FILE, SUBMISSIONS_FILE]:
        if not os.path.exists(f):
            with open(f, 'w') as fh:
                json.dump([], fh)

def _load(filepath):
    ensure_dirs()
    with open(filepath, 'r') as f:
        return json.load(f)

def _save(filepath, data):
    ensure_dirs()
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2)

class LeadStore:
    """Manage qualified leads generated by the system."""
    
    @staticmethod
    def add_lead(lead_data: dict) -> dict:
        leads = _load(LEADS_FILE)
        lead = {
            'id': str(uuid.uuid4())[:8],
            'name': lead_data.get('name', 'Unknown'),
            'email': lead_data.get('email', ''),
            'company': lead_data.get('company', ''),
            'phone': lead_data.get('phone', ''),
            'score': lead_data.get('score', 0),
            'tier': lead_data.get('tier', 'Cold'),
            'source': lead_data.get('source', 'chatbot'),
            'notes': lead_data.get('notes', ''),
            'status': 'new',
            'delivered_to': lead_data.get('client_id', ''),
            'created_at': datetime.now().isoformat(),
            'conversation_log': lead_data.get('conversation_log', '')
        }
        leads.append(lead)
        _save(LEADS_FILE, leads)
        return lead
    
    @staticmethod
    def get_leads(client_id=None, status=None, limit=50):
        leads = _load(LEADS_FILE)
        if client_id:
            leads = [l for l in leads if l['delivered_to'] == client_id]
        if status:
            leads = [l for l in leads if l['status'] == status]
        return sorted(leads, key=lambda x: x['created_at'], reverse=True)[:limit]
    
    @staticmethod
    def get_lead(lead_id: str) -> dict:
        leads = _load(LEADS_FILE)
        for l in leads:
            if l['id'] == lead_id:
                return l
        return None
    
    @staticmethod
    def update_status(lead_id: str, status: str) -> bool:
        leads = _load(LEADS_FILE)
        for l in leads:
            if l['id'] == lead_id:
                l['status'] = status
                l['updated_at'] = datetime.now().isoformat()
                _save(LEADS_FILE, leads)
                return True
        return False
    
    @staticmethod
    def count_by_status(client_id=None):
        leads = _load(LEADS_FILE)
        if client_id:
            leads = [l for l in leads if l['delivered_to'] == client_id]
        counts = {'new': 0, 'contacted': 0, 'qualified': 0, 'closed': 0, 'lost': 0}
        for l in leads:
            status = l.get('status', 'new')
            if status in counts:
                counts[status] += 1
        return counts

class ClientStore:
    """Manage client accounts."""
    
    @staticmethod
    def add_client(data: dict) -> dict:
        clients = _load(CLIENTS_FILE)
        client = {
            'id': str(uuid.uuid4())[:8],
            'name': data.get('name', ''),
            'email': data.get('email', ''),
            'company': data.get('company', ''),
            'package': data.get('package', 'Starter'),
            'addons': data.get('addons', []),
            'questionnaire': data.get('questionnaire', {}),
            'documents': data.get('documents', {}),
            'leads_delivered': 0,
            'status': 'active',
            'created_at': datetime.now().isoformat()
        }
        clients.append(client)
        _save(CLIENTS_FILE, clients)
        return client
    
    @staticmethod
    def get_clients(limit=100):
        clients = _load(CLIENTS_FILE)
        return sorted(clients, key=lambda x: x['created_at'], reverse=True)[:limit]
    
    @staticmethod
    def get_client(client_id: str) -> dict:
        clients = _load(CLIENTS_FILE)
        for c in clients:
            if c['id'] == client_id:
                return c
        return None
    
    @staticmethod
    def update_leads_count(client_id: str, count: int):
        clients = _load(CLIENTS_FILE)
        for c in clients:
            if c['id'] == client_id:
                c['leads_delivered'] = c.get('leads_delivered', 0) + count
                _save(CLIENTS_FILE, clients)
                return True
        return False

class SubmissionStore:
    """Store questionnaire submissions."""
    
    @staticmethod
    def save(data: dict, doc_id: str) -> dict:
        subs = _load(SUBMISSIONS_FILE)
        sub = {
            'id': doc_id,
            'data': data,
            'generated_at': datetime.now().isoformat()
        }
        subs.append(sub)
        _save(SUBMISSIONS_FILE, subs)
        return sub
    
    @staticmethod
    def get_all(limit=50):
        subs = _load(SUBMISSIONS_FILE)
        return sorted(subs, key=lambda x: x['generated_at'], reverse=True)[:limit]
